(part "W65C02S6TPG-14"
    (packageRef "DIP1524W56P254L5207H508Q40N")
    (interface
        (port "1" (symbPinId 1) (portName "VPB") (portType INOUT))
        (port "2" (symbPinId 2) (portName "RDY") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PHI1O") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IRQB") (portType INPUT))
        (port "5" (symbPinId 5) (portName "MLB") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NMIB") (portType INPUT))
        (port "7" (symbPinId 7) (portName "SYNC") (portType OUTPUT))
        (port "8" (symbPinId 8) (portName "VDD") (portType POWER))
        (port "9" (symbPinId 9) (portName "A0") (portType OUTPUT))
        (port "10" (symbPinId 10) (portName "A1") (portType OUTPUT))
        (port "11" (symbPinId 11) (portName "A2") (portType OUTPUT))
        (port "12" (symbPinId 12) (portName "A3") (portType OUTPUT))
        (port "13" (symbPinId 13) (portName "A4") (portType OUTPUT))
        (port "14" (symbPinId 14) (portName "A5") (portType OUTPUT))
        (port "15" (symbPinId 15) (portName "A6") (portType OUTPUT))
        (port "16" (symbPinId 16) (portName "A7") (portType OUTPUT))
        (port "17" (symbPinId 17) (portName "A8") (portType OUTPUT))
        (port "18" (symbPinId 18) (portName "A9") (portType OUTPUT))
        (port "19" (symbPinId 19) (portName "A10") (portType OUTPUT))
        (port "20" (symbPinId 20) (portName "A11") (portType OUTPUT))
        (port "21" (symbPinId 21) (portName "VSS") (portType GROUND))
        (port "22" (symbPinId 22) (portName "A12") (portType OUTPUT))
        (port "23" (symbPinId 23) (portName "A13") (portType OUTPUT))
        (port "24" (symbPinId 24) (portName "A14") (portType OUTPUT))
        (port "25" (symbPinId 25) (portName "A15") (portType OUTPUT))
        (port "26" (symbPinId 26) (portName "D7") (portType OUTPUT))
        (port "27" (symbPinId 27) (portName "D6") (portType OUTPUT))
        (port "28" (symbPinId 28) (portName "D5") (portType OUTPUT))
        (port "29" (symbPinId 29) (portName "D4") (portType OUTPUT))
        (port "30" (symbPinId 30) (portName "D3") (portType OUTPUT))
        (port "31" (symbPinId 31) (portName "D2") (portType OUTPUT))
        (port "32" (symbPinId 32) (portName "D1") (portType OUTPUT))
        (port "33" (symbPinId 33) (portName "D0") (portType OUTPUT))
        (port "34" (symbPinId 34) (portName "RWB") (portType OUTPUT))
        (port "35" (symbPinId 35) (portName "NC") (portType INOUT))
        (port "36" (symbPinId 36) (portName "BE") (portType INOUT))
        (port "37" (symbPinId 37) (portName "PHI2") (portType INOUT))
        (port "38" (symbPinId 38) (portName "SOB") (portType INOUT))
        (port "39" (symbPinId 39) (portName "PHI2O") (portType INOUT))
        (port "40" (symbPinId 40) (portName "RESB") (portType INPUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "955-W65C02S6TPG-14")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Western-Design-Center-WDC/W65C02S6TPG-14?qs=opBjA1TV903lvWo9AEKH5w%3D%3D")
    (property "Manufacturer_Name" "Western Design Center (WDC)")
    (property "Manufacturer_Part_Number" "W65C02S6TPG-14")
    (property "Description" "Microprocessors - MPU 8-bit Microprocessor")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/W65C02S6TPG-14.pdf")
    (property "symbolName1" "W65C02S6TPG-14")
)
